trigger: none

pool:
  name: infra_agentpool

stages:
  - stage: terraforminstall
    displayName: terraforminstall
    jobs:
      - job: terraforminstall
        displayName: terraforminstall
        steps:
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'

          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)\01_vm_code/01_environment/01_preprod'
              backendServiceArm: 'infra-azure-connection'
              backendAzureRmStorageAccountName: 'bappastatestorage'
              backendAzureRmContainerName: 'statecontainer'
              backendAzureRmKey: 'vm.tfstate'
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'validate'
              workingDirectory: '$(System.DefaultWorkingDirectory)\01_vm_code/01_environment/01_preprod'

