trigger: none

pool:
  name: infra_agentpool

stages:
  - stage: terraforminstall
    displayName: terraform app initiallize
    jobs:
      - job: terraforminstall
        displayName: terraform app install
        steps:
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'

          - task: TerraformTask@5
            displayName: "terraform init"
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)\01_vm_code/01_environment/01_preprod'
              backendServiceArm: 'infra-azure-connection'
              backendAzureRmStorageAccountName: 'bappastatestorage'
              backendAzureRmContainerName: 'statecontainer'
              backendAzureRmKey: 'vm.tfstate'
          - task: TerraformTask@5
            displayName: "validate"
            inputs:
              provider: 'azurerm'
              command: 'validate'
              workingDirectory: '$(System.DefaultWorkingDirectory)\01_vm_code/01_environment/01_preprod'

  - stage: terraformplan
    jobs:
      - job: terraform_plan
        displayName: execute plan
        steps:
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'

          - task: TerraformTask@5
            displayName: "terraform init"
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)\01_vm_code/01_environment/01_preprod'
              backendServiceArm: 'infra-azure-connection'
              backendAzureRmStorageAccountName: 'bappastatestorage'
              backendAzureRmContainerName: 'statecontainer'
              backendAzureRmKey: 'vm.tfstate'
          - task: TerraformTask@5
            displayName: plan will execute
            inputs:
              provider: 'azurerm'
              command: 'plan'
              workingDirectory: '$(System.DefaultWorkingDirectory)\01_vm_code/01_environment/01_preprod'
              environmentServiceNameAzureRM: 'infra-azure-connection'